name: "Frogbot by JFrog"
description: "JFrog Frogbot is a Git bot that scans your pull requests and repositories for security vulnerabilities."
author: "JFrog"
inputs:
  version:
    description: "Frogbot version"
    default: "latest"
    required: false
runs:
  using: "node16"
  main: "action/lib/main.js"
branding:
  icon: "terminal"
  color: "green"
